### ISSUE TITLE
页眉居中

### ISSUE THREAD

**Issue by liguohao1997** [wyqy/TongjiThesis_Proto#2]
您好，我看最新的要求是页眉居中，只需要本章标题即可，请问一下，在哪个文件可以修改命令，谢谢啦

**Comment by wyqy** [comment]
页眉和页脚的控制有两部分:
一部分是正文(还包括封面, 引用), 使用的是 fancyhdr 宏包中的 \fancypagestyle 命令配置页眉和页脚的样式
另一部分是除上面之外的其余部分(包括摘要, 目录, 索引, 附录等), 使用的是初始 TongjiThesis 模板里面的 \tongji@chapter 命令
相关的代码都在 tongjithesis.cls 文件里, 可以通过搜索关键词的方式找一下

我刚刚提交了一个新版本, 引入了一个名为 styleheadercentered 的开关, 控制正文页眉和页脚是否居中
不过现在我没有最新的论文要求, 如果你方便的话可以发我一下, 我对照着完善一下, 或者你也可以在此基础上增补?

**Comment by liguohao1997** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    ***@***.***命令，另外，现在的页眉不需要写同济大学了，这部分我也做了修改。我把修改后的tongjithesis.cls 文件，还有最新的要求发给您。
    
        
            
        
    
    
      
    
        
                    
            
                
                    
                            
                                
                            
                            
                                liguohao66
                            
                    
                        
                            
                                    ***@***.***
                            
                        
                
            
        
        
    
 
    

  
    ---- 回复的原邮件 ----
  
  
    
      
        
         发件人 
        
        
            Jingze ***@***.***>
            
        
      
      
        
         发送日期 
        
        
        2024年07月22日 06:23
        
      
      
        
         收件人 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         抄送人 
        
        
          
            ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         主题 
        
        
              Re: [wyqy/TongjiThesis_Proto] 页眉居中 (Issue #2)
        
      
    
  
  
页眉和页脚的控制有两部分:
一部分是正文(还包括封面, 引用), 使用的是 fancyhdr 宏包中的 \fancypagestyle 命令配置页眉和页脚的样式
另一部分是除上面之外的其余部分(包括摘要, 目录, 索引, 附录等), 使用的是初始 TongjiThesis 模板里面的 ***@***.*** 命令
相关的代码都在 tongjithesis.cls 文件里, 可以通过搜索关键词的方式找一下
我刚刚提交了一个新版本, 引入了一个名为 styleheadercentered 的开关, 控制正文页眉和页脚是否居中
不过现在我没有最新的论文要求, 如果你方便的话可以发我一下, 我对照着完善一下, 或者你也可以在此基础上增补?

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by wyqy** [comment]
我这里没有收到文件, 可能是邮件附件被拦截了? 
方便的话, 可以用邮箱直接发我吗, 我的邮箱是 [youjingze@msn.cn](mailto:youjingze@msn.cn) Thanks~

**Comment by liguohao1997** [comment]
好的，没问题
---- Replied Message ----
FromJingze ***@***.***>Date07/23/2024 08:07 ***@***.***> ***@***.***>,
***@***.***>SubjectRe: [wyqy/TongjiThesis_Proto] 页眉居中 (Issue #2)
我这里没有收到文件, 可能是邮件附件被拦截了?
方便的话, 可以用邮箱直接发我吗, 我的邮箱是 ***@***.*** Thanks~

**Comment by wyqy** [comment]
现在发布了新的版本, 能够通过 ``newstyle`` 开关控制生成的页眉样式 (默认/true => 生成新版, false => 生成旧版)
感谢指正

**Comment by liguohao1997** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    非常感谢您的付出，点赞
    
        
            
        
    
    
      
    
        
                    
            
                
                    
                            
                                
                            
                            
                                liguohao66
                            
                    
                        
                            
                                    ***@***.***
                            
                        
                
            
        
        
    
 
    

  
    ---- 回复的原邮件 ----
  
  
    
      
        
         发件人 
        
        
            Jingze ***@***.***>
            
        
      
      
        
         发送日期 
        
        
        2024年07月28日 00:35
        
      
      
        
         收件人 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         抄送人 
        
        
          
            ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         主题 
        
        
              Re: [wyqy/TongjiThesis_Proto] 页眉居中 (Issue #2)
        
      
    
  
  
现在发布了新的版本, 能够通过 newstyle 开关控制生成的页眉样式 (默认/true => 生成新版, false => 生成旧版)
感谢指正

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
