### ISSUE TITLE
overleaf中上传此仓库的zip后无法编译出pdf

### ISSUE THREAD

**Issue by Ink-core** [wyqy/TongjiThesis_Proto#4]
希望作者可以适配出overleaf上可套用的模板
有如下报错信息：
“This compile didn’t produce a PDF. This can happen if:
There is an unrecoverable LaTeX error. If there are LaTeX errors shown below or in the raw logs, please try to fix them and compile again.
The document environment contains no content. If it’s empty, please add some content and compile again.
This project contains a file called output.pdf. If that file exists, please rename it and compile again.
140 log messages total. Showing the first 100
 Tip: Try to fix the first error and recompile. Often one error causes many later error messages. You can  to focus on fixing errors. We recommend fixing errors as soon as possible; letting them accumulate may lead to hard-to-debug and fatal errors. Learn more

If you need to see the full logs, you can still download them or view the raw logs below.”
<img width="1233" alt="overleaf报错信息" src="https://github.com/user-attachments/assets/ba2b1ec4-ec8e-4d05-be38-7e0dc301a58e">

**Comment by wyqy** [comment]
你好, 我测试了一下, 在使用 TeXLive 2023/2024  + XeLaTeX 的情况下, 是可以用 Overleaf 编译的.

不过, 如果使用 pdflatex 编译的话就会出现和你的附图类似的错误. 这是一个已知问题, 因为该模板显式依赖 xecjk 宏包, 而 xecjk 宏包只能在 xelatex 下使用. 所以 readme 里要求必须使用 xelatex 命令才能编译.

可以麻烦再测试下, 如果指定使用 2023 / 2024 版本的 TeXLive, 以及 xelatex 命令编译的话还会有上面的问题吗, 谢谢!

**Comment by Ink-core** [comment]
你好，那可能是overleaf自身的编译设置问题，无法支持xecjk包

**Comment by wyqy** [comment]
可能我刚刚的表述有点不清楚, 如果我的测试没问题, 你只需要把 overleaf 编译选项里的编译器改成 XeLaTeX 就可以了, 我这边这样是可以成功编译的

**Comment by Ink-core** [comment]
👌，多谢

**Comment by Ink-core** [comment]
英文摘要最后的关键词应该是Key Words加粗，但是此模板写成了Abstract不加粗
